### ISSUE TITLE
One Piece and Naruto won't show up in show list

### ISSUE THREAD

**Issue by Artlinkz** [GU5TAF/HorribleSubs-Squire-Stream#2]
can't manage to find those 2 shows

**Comment by GU5TAF** [comment]
I've been having issues mapping the HorribleSubs episode number with the TVDB season and episode.
One Piece episode 700 is for example season 17 episode 73 or something along those lines.
There's really no way to solve this without 700 manual edits (one for each episode).

**Comment by Artlinkz** [comment]
that’s what i thought indeed it’s a mess with their counting of seasons / episodes… anyway i was just asking, because it was working at the beginning and later on not anymore…

but good job so far man, many thanks 
hope you’ll find a solutions… maybe getting an episode list without seasons, i don’t know i’m just thinking out loud…
